# pre-commit-config obtained from https://github.com/ros-planning/moveit2/blob/main/.pre-commit-config.yaml
# Thank you to PICKNIK Robotics for sharing your config
#
# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
        exclude: CMakeLists.txt
      - id: check-toml
      - id: check-xml
        files: '.*\.(xml|launch)'
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
        exclude: CMakeLists.txt
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - "@prettier/plugin-xml"

  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: Format files with ClangFormat.
        entry: clang-format-12
        language: system
        files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|js|m|proto|vert)$
        args: ["-fallback-style=none", "-i"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: ["--write-changes", "--ignore-words=.codespell_words"]
        exclude: CHANGELOG.rst
